# Generated by Django 4.0.10 on 2025-11-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeejob',
            name='pay_rate',
            field=models.FloatField(blank=True, default=0, max_length=6, null=True),
        ),
    ]
