# Generated by Django 4.0.10 on 2025-11-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_employeejob_pay_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobbase',
            name='department',
            field=models.CharField(choices=[('Management', 'Management'), ('FOH', 'Front of House'), ('BOH', 'Back of House'), ('Maintenance', 'Maintenance')], max_length=15, null=True),
        ),
    ]
