# Generated by Django 4.0.10 on 2025-10-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_location_alter_customuser_email_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra XLarge')], max_length=15, null=True),
        ),
    ]
